package com.national.computer.servlets;


import java.io.*;
import java.sql.*;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;import java.sql.PreparedStatement;
public class RegistrationServlet extends HttpServlet
{
   Connection con;
   public void init()
    {
       try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","scott","tiger"); 
        }
       catch(Exception e)
        {
           System.out.println(e);
        }
    }
  public void doGet(HttpServletRequest req,HttpServletResponse res)
   {
      try
       {
           String s=req.getParameter("id");
           String s1=req.getParameter("fname");
           String s2=req.getParameter("lname");
           String s3=req.getParameter("uname");
           String s4=req.getParameter("pword");
           String s5=req.getParameter("email");
           PreparedStatement pstmt=con.prepareStatement("insert into info2 values(?,?,?,?,?,?)");
           pstmt.setString(1,s);
           pstmt.setString(2,s1);
           pstmt.setString(3,s2);
           pstmt.setString(4,s3);
           pstmt.setString(5,s4);
           pstmt.setString(6,s5);
           pstmt.executeUpdate();
           PrintWriter pw=res.getWriter();
           pw.println("<html><head><style>@charset \"UTF-8\";\r\n"
              		+ "final css html,body{\r\n"
              		+ "margin:0;\r\n"
              		+ "padding:0;\r\n"
              		+ "height:100%;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".bg-image{\r\n"
              		+ "position:fixed;\r\n"
              		+ "top:0;\r\n"
              		+ "left:0;\r\n"
              		+ "width:100vw;\r\n"
              		+ "height:100vh;\r\n"
              		+ "z-index:-1;\r\n"
              		+ "\r\n"
              		+ "background-repeat:no-repeat;\r\n"
              		+ "background-position:center center;\r\n"
              		+ "background-size:cover;   \r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ ".home-bg{\r\n"
              		+ "background-image:url('../images/home1.png');\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".upload-bg{\r\n"
              		+ "background-image:url('../images/home.jpg');\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".list-bg{\r\n"
              		+ "background-image:url('../images/home.jpg');\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".success-bg{\r\n"
              		+ "background-image:url('../images/home.jpg');\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ ".container{\r\n"
              		+ "width:420px;\r\n"
              		+ "position:absolute;\r\n"
              		+ "top:50%;\r\n"
              		+ "left:50%;\r\n"
              		+ "transform:translate(-50%,-50%);\r\n"
              		+ "background:rgba(255,255,255,0.15);\r\n"
              		+ "padding:30px;\r\n"
              		+ "border-radius:15px;\r\n"
              		+ "text-align:center;\r\n"
              		+ "backdrop-filter:blur(12px);\r\n"
              		+ "color:white;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "    article {\r\n"
              		+ "      background: #fff5e6;\r\n"
              		+ "      padding: 15px;\r\n"
              		+ "      border-left: 5px solid #ff9800;\r\n"
              		+ "      margin-bottom: 15px;\r\n"
              		+ "      border-radius: 6px;\r\n"
              		+ "      transition: 0.3s;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    article:hover {\r\n"
              		+ "      background: #ffeacf;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    aside {\r\n"
              		+ "       background: var(--card);\r\n"
              		+ "      padding: 1.5rem;\r\n"
              		+ "      border-radius: 1.5rem;\r\n"
              		+ "      box-shadow: 0 10px 25px rgba(0,0,0,0.5);\r\n"
              		+ "      transition: transform 0.3s;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    aside:hover {\r\n"
              		+ " transform: translateY(-5px);   \r\n"
              		+ "  }\r\n"
              		+ "\r\n"
              		+ "   \r\n"
              		+ "details {\r\n"
              		+ "      \r\n"
              		+ "      padding: 1.5rem;\r\n"
              		+ "      border-radius: 1.5rem;\r\n"
              		+ "      box-shadow: 0 10px 25px rgba(0,0,0,0.5);\r\n"
              		+ "      transition: transform 0.3s;\r\n"
              		+ "            color: var(--accent);\r\n"
              		+ "      \r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    details summary {\r\n"
              		+ "      font-weight: bold;\r\n"
              		+ "      cursor: pointer;\r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    details p {\r\n"
              		+ "     \r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }    \r\n"
              		+ " .fa {\r\n"
              		+ "padding: 20px;\r\n"
              		+ "font-size: 10px;\r\n"
              		+ "width: 10px;\r\n"
              		+ "text-align: center;\r\n"
              		+ "text-decoration: none;\r\n"
              		+ "margin: 5px 2px;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".fa-instagram {\r\n"
              		+ "background:non;\r\n"
              		+ "color: gold;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ ".fa:hover {\r\n"
              		+ "opacity: 0.7;\r\n"
              		+ "}\r\n"
              		+ ".container {\r\n"
              		+ "    width: 400px;\r\n"
              		+ "    margin: 100px auto;\r\n"
              		+ "    background: rgba(255, 255, 255, 0.9);\r\n"
              		+ "    padding: 30px;\r\n"
              		+ "    border-radius: 10px;\r\n"
              		+ "    box-shadow: 0 0 15px #000;\r\n"
              		+ "    text-align: center;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "h2 {\r\n"
              		+ "    margin-bottom: 20px;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "input[type=\"file\"] {\r\n"
              		+ "    width: 100%;\r\n"
              		+ "    padding: 8px;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "input[type=\"submit\"] {\r\n"
              		+ "    margin-top: 15px;\r\n"
              		+ "    padding: 8px 15px;\r\n"
              		+ "    background: #2c7be5;\r\n"
              		+ "    border: none;\r\n"
              		+ "    color: white;\r\n"
              		+ "    cursor: pointer;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "input[type=\"submit\"]:hover {\r\n"
              		+ "    background: #1a5ec8;\r\n"
              		+ "}\r\n"
              		+ "input[type=\"reset\"] {\r\n"
              		+ "    margin-top: 15px;\r\n"
              		+ "    padding: 8px 15px;\r\n"
              		+ "    background: #2c7be5;\r\n"
              		+ "    border: none;\r\n"
              		+ "    color: white;\r\n"
              		+ "    cursor: pointer;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "input[type=\"reset\"]:hover {\r\n"
              		+ "    background: #1a5ec8;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "a {\r\n"
              		+ "    text-decoration: none;\r\n"
              		+ "    color: #2c7be5;\r\n"
              		+ "}\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "    :root {\r\n"
              		+ "      --bg: #0f172a;\r\n"
              		+ "      --card: #111827;\r\n"
              		+ "      --accent: #38bdf8;\r\n"
              		+ "      --text: #e5e7eb;\r\n"
              		+ "      --muted: #9ca3af;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    * {\r\n"
              		+ "      margin: 0;\r\n"
              		+ "      padding: 0;\r\n"
              		+ "      box-sizing: border-box;\r\n"
              		+ "      font-family: 'Inter', sans-serif;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    body {\r\n"
              		+ "      background: linear-gradient(135deg, #020617, #0f172a);\r\n"
              		+ "      color: var(--text);\r\n"
              		+ "      min-height: 100vh;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    header {\r\n"
              		+ "      background: rgba(2, 6, 23, 0.9);\r\n"
              		+ "      position: sticky;\r\n"
              		+ "      top: 0;\r\n"
              		+ "      z-index: 100;\r\n"
              		+ "      box-shadow: 0 4px 20px rgba(0,0,0,0.5);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .nav {\r\n"
              		+ "      max-width: 1200px;\r\n"
              		+ "      margin: auto;\r\n"
              		+ "      display: flex;\r\n"
              		+ "      justify-content: space-between;\r\n"
              		+ "      align-items: center;\r\n"
              		+ "      padding: 1rem 2rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .logo {\r\n"
              		+ "      font-size: 1.5rem;\r\n"
              		+ "      font-weight: 700;\r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    nav a {\r\n"
              		+ "      margin-left: 1.5rem;\r\n"
              		+ "      text-decoration: none;\r\n"
              		+ "      color: var(--text);\r\n"
              		+ "      font-weight: 500;\r\n"
              		+ "      transition: color 0.3s;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    nav a:hover {\r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .hero {\r\n"
              		+ "      max-width: 1200px;\r\n"
              		+ "      margin: auto;\r\n"
              		+ "      padding: 6rem 2rem;\r\n"
              		+ "      text-align: center;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .hero h1 {\r\n"
              		+ "      font-size: 3rem;\r\n"
              		+ "      margin-bottom: 1rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .hero p {\r\n"
              		+ "      color: var(--muted);\r\n"
              		+ "      font-size: 1.2rem;\r\n"
              		+ "      max-width: 700px;\r\n"
              		+ "      margin: auto;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .btn {\r\n"
              		+ "      display: inline-block;\r\n"
              		+ "      margin-top: 2rem;\r\n"
              		+ "      padding: 0.8rem 2rem;\r\n"
              		+ "      background: var(--accent);\r\n"
              		+ "      color: #020617;\r\n"
              		+ "      border-radius: 2rem;\r\n"
              		+ "      text-decoration: none;\r\n"
              		+ "      font-weight: 600;\r\n"
              		+ "      transition: transform 0.3s, box-shadow 0.3s;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .btn:hover {\r\n"
              		+ "      transform: translateY(-3px);\r\n"
              		+ "      box-shadow: 0 10px 25px rgba(56,189,248,0.4);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    section {\r\n"
              		+ "      max-width: 1200px;\r\n"
              		+ "      margin: auto;\r\n"
              		+ "      padding: 4rem 2rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    section h2 {\r\n"
              		+ "      font-size: 2rem;\r\n"
              		+ "      margin-bottom: 1.5rem;\r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .grid {\r\n"
              		+ "      display: grid;\r\n"
              		+ "      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\r\n"
              		+ "      gap: 1.5rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .card {\r\n"
              		+ "      background: var(--card);\r\n"
              		+ "      padding: 1.5rem;\r\n"
              		+ "      border-radius: 1.5rem;\r\n"
              		+ "      box-shadow: 0 10px 25px rgba(0,0,0,0.5);\r\n"
              		+ "      transition: transform 0.3s;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .card:hover {\r\n"
              		+ "      transform: translateY(-5px);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .card h3 {\r\n"
              		+ "      margin-bottom: 0.5rem;\r\n"
              		+ "      color: var(--accent);\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    .card p, .card ul {\r\n"
              		+ "      color: var(--muted);\r\n"
              		+ "      font-size: 0.95rem;\r\n"
              		+ "      line-height: 1.6;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    pre {\r\n"
              		+ "      background: #020617;\r\n"
              		+ "      padding: 1rem;\r\n"
              		+ "      border-radius: 1rem;\r\n"
              		+ "      overflow-x: auto;\r\n"
              		+ "      color: #38bdf8;\r\n"
              		+ "      font-size: 0.9rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    footer {\r\n"
              		+ "      text-align: center;\r\n"
              		+ "      padding: 2rem;\r\n"
              		+ "      background: #020617;\r\n"
              		+ "      color: var(--muted);\r\n"
              		+ "      margin-top: 4rem;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "    html {\r\n"
              		+ "      scroll-behavior: smooth;\r\n"
              		+ "    }\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "\r\n"
              		+ "      </style></head><body><center>");

           pw.println("<header>");
           pw.println("<h2>You Have Successfully Registered</h2>");
           pw.println("</header>");
           pw.println(" <header>\r\n"
            		+ "    <div class=\"nav\">\r\n"
            		+ "      <div class=\"logo\">Secure File Sharing System</div>\r\n"
            		+ "      <nav>\r\n"
            		+ "        <a href=\"#login\">Login</a>\r\n"
            		+ "        <a href=\"#contact\">Contact</a>\r\n"
            		+ "      </nav>\r\n"
            		+ "    </div>\r\n"
            		+ "  </header>");
           pw.println("<section id=\"login\">\r\n"
           		+ "    <div class=\"grid\">\r\n"
           		+ "      <div class=\"card\">\r\n"
           		+ "          <h2>User Login</h2>\r\n"
           		+ "        <p>Thank You for registering with us. Now you can login by using your registered username/password</p>\r\n"
           		+ "        <a href=login1 class=\"btn\">Login</a> \r\n"
           		+ "      </div>\r\n"
           		+ "      </div>\r\n"
           		+ "  </section>\r\n"
           		+ "");
           pw.println("<section id=\"contact\">\r\n"
              		+ "  <div class=\"grid\">\r\n"
              		+ "  <details>\r\n"
              		+ "    <summary><h2>About Me</h2></summary>\r\n"
              		+ "     <div class=\"card\">\r\n"
              		+ "        <h3>A short info about me</h3>\r\n"
              		+ "      <p>I'm a web developer, I love developing web applications using Java Technologies</p>\r\n"
              		+ "      </div>\r\n"
              		+ "    </details>\r\n"
              		+ "     <details>\r\n"
              		+ "    <summary><h2>Developer Name</h2></summary>\r\n"
              		+ "      <div class=\"card\">\r\n"
              		+ "        <h3>Developer name goes below:-</h3>\r\n"
              		+ "   <p>This project has been developed by:</p>\r\n"
              		+ "      <p><i><b>Prathamesh Kumawat :)</b></i></p>\r\n"
              		+ "     </div>\r\n"
              		+ "    </details>\r\n"
              		+ "  <details>\r\n"
              		+ "   <summary> <h2>Follow Me</h2></summary>\r\n"
              		+ "       <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
              		+ "    <a href=\"https://www.instagram.com/pratham_17498/\" class=\"fa fa-instagram\"></a>\r\n"
              		+ "    </details>\r\n"
              		+ "    </div>\r\n"
              		+ "</section>\r\n"
              		+ "<footer>\r\n"
              		+ "  <p><h5><u><b>(Note:- This Project Is A Personal Project and All Work Done Is My Original Work.)</b></u><h5></p><br>\r\n"
              		+ "   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
              		+ "  &copy;Follow Me:<a href=\"https://www.instagram.com/pratham_17498/\" class=\"fa fa-instagram\"></a>\r\n"
              		+ "</footer>\r\n"
              		+ "</body>\r\n"
              		+ "</html>");
       }
      catch(Exception e)
       {
          System.out.println(e);
       }
   }
}